"""dashboard views and discussion

Revision ID: 991448cb5458
Revises: eab7660183f4
Create Date: 2026-09-22 13:38:24.111211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991448cb5458'
down_revision: Union[str, Sequence[str], None] = 'eab7660183f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['dashboard_cards.id'], name=op.f('fk_dashboard_comments_card_id_dashboard_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dashboard_comments_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_comments'))
    )
    op.create_index(op.f('ix_dashboard_comments_card_id'), 'dashboard_comments', ['card_id'], unique=False)
    op.add_column('dashboards', sa.Column('view_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_dashboards_view_id'), 'dashboards', ['view_id'])
    op.create_foreign_key(op.f('fk_dashboards_view_id_views'), 'dashboards', 'views', ['view_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_dashboards_view_id_views'), 'dashboards', type_='foreignkey')
    op.drop_constraint(op.f('uq_dashboards_view_id'), 'dashboards', type_='unique')
    op.drop_column('dashboards', 'view_id')
    op.drop_index(op.f('ix_dashboard_comments_card_id'), table_name='dashboard_comments')
    op.drop_table('dashboard_comments')
    # ### end Alembic commands ###
