"""goals and sub-teams

Revision ID: 6170a5530ac2
Revises: 5249f258f1f1
Create Date: 2026-09-22 20:22:48.426024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6170a5530ac2'
down_revision: Union[str, Sequence[str], None] = '5249f258f1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('folder', sa.String(length=80), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('owner_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_goals_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_goals_team_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_goals_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_index(op.f('ix_goals_team_id'), 'goals', ['team_id'], unique=False)
    op.create_index(op.f('ix_goals_workspace_id'), 'goals', ['workspace_id'], unique=False)
    op.create_table('goal_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('start_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('task_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('list_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('orderindex', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('number', 'currency', 'true_false', 'tasks')", name=op.f('ck_goal_targets_kind')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_goal_targets_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_goal_targets_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_targets'))
    )
    op.create_index(op.f('ix_goal_targets_goal_id'), 'goal_targets', ['goal_id'], unique=False)
    op.create_table('goal_check_ins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['goal_targets.id'], name=op.f('fk_goal_check_ins_target_id_goal_targets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goal_check_ins_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_check_ins'))
    )
    op.create_index(op.f('ix_goal_check_ins_target_id'), 'goal_check_ins', ['target_id'], unique=False)
    op.add_column('teams', sa.Column('parent_team_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_teams_parent_team_id'), 'teams', ['parent_team_id'], unique=False)
    op.create_foreign_key(op.f('fk_teams_parent_team_id_teams'), 'teams', 'teams', ['parent_team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_teams_parent_team_id_teams'), 'teams', type_='foreignkey')
    op.drop_index(op.f('ix_teams_parent_team_id'), table_name='teams')
    op.drop_column('teams', 'parent_team_id')
    op.drop_index(op.f('ix_goal_check_ins_target_id'), table_name='goal_check_ins')
    op.drop_table('goal_check_ins')
    op.drop_index(op.f('ix_goal_targets_goal_id'), table_name='goal_targets')
    op.drop_table('goal_targets')
    op.drop_index(op.f('ix_goals_workspace_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_team_id'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
