"""custom fields and table view

Revision ID: 762c61628de1
Revises: 9e843c596a8a
Create Date: 2026-09-22 11:39:28.834933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '762c61628de1'
down_revision: Union[str, Sequence[str], None] = '9e843c596a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

VIEW_TYPES_OLD = "('list', 'board', 'calendar', 'dashboard', 'workload', 'overview')"
VIEW_TYPES_NEW = "('list', 'board', 'calendar', 'dashboard', 'workload', 'overview', 'table')"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('list_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'long_text', 'number', 'money', 'dropdown', 'labels', 'date', 'checkbox', 'email', 'phone', 'url', 'rating', 'progress', 'people', name='field_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('orderindex', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(space_id, folder_id, list_id) = 1', name=op.f('ck_custom_fields_one_parent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_custom_fields_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_custom_fields_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_custom_fields_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_custom_fields_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_fields'))
    )
    op.create_index(op.f('ix_custom_fields_folder_id'), 'custom_fields', ['folder_id'], unique=False)
    op.create_index(op.f('ix_custom_fields_list_id'), 'custom_fields', ['list_id'], unique=False)
    op.create_index(op.f('ix_custom_fields_space_id'), 'custom_fields', ['space_id'], unique=False)
    op.create_table('task_field_values',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['custom_fields.id'], name=op.f('fk_task_field_values_field_id_custom_fields'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_field_values_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_task_field_values_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('task_id', 'field_id', name=op.f('pk_task_field_values'))
    )
    op.create_index(op.f('ix_task_field_values_field_id'), 'task_field_values', ['field_id'], unique=False)
    # ### end Alembic commands ###

    # Hand-written: allow the new 'table' view type in the enum's CHECK.
    op.drop_constraint(op.f('ck_views_view_type'), 'views', type_='check')
    op.create_check_constraint(op.f('ck_views_view_type'), 'views', f"view_type IN {VIEW_TYPES_NEW}")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM views WHERE view_type = 'table'")
    op.drop_constraint(op.f('ck_views_view_type'), 'views', type_='check')
    op.create_check_constraint(op.f('ck_views_view_type'), 'views', f"view_type IN {VIEW_TYPES_OLD}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_field_values_field_id'), table_name='task_field_values')
    op.drop_table('task_field_values')
    op.drop_index(op.f('ix_custom_fields_space_id'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_fields_list_id'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_fields_folder_id'), table_name='custom_fields')
    op.drop_table('custom_fields')
    # ### end Alembic commands ###
