"""people admin audit joiner

Revision ID: 8dc9bb4f3720
Revises: c54d64d05b70
Create Date: 2026-09-22 16:17:18.146023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dc9bb4f3720'
down_revision: Union[str, Sequence[str], None] = 'c54d64d05b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_kind', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('target_label', sa.String(length=300), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_workspace_time', 'audit_events', ['workspace_id', 'created_at'], unique=False)
    op.create_table('person_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('rule_key', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_person_tasks_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_person_tasks_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_person_tasks_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_tasks')),
    sa.UniqueConstraint('workspace_id', 'user_id', 'rule_key', name='one_per_rule')
    )
    op.create_index(op.f('ix_person_tasks_task_id'), 'person_tasks', ['task_id'], unique=False)
    op.create_index(op.f('ix_person_tasks_user_id'), 'person_tasks', ['user_id'], unique=False)
    op.add_column('users', sa.Column('avatar_key', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_sign_in_provider', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('last_second_factor', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('workspace_members', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('workspace_members', sa.Column('marriage_anniversary', sa.Date(), nullable=True))
    op.add_column('workspace_members', sa.Column('takes_interviews', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('workspace_members', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workspace_members', sa.Column('deactivated_by', sa.String(length=128), nullable=True))
    op.create_foreign_key(op.f('fk_workspace_members_deactivated_by_users'), 'workspace_members', 'users', ['deactivated_by'], ['id'], ondelete='SET NULL')
    op.add_column('workspaces', sa.Column('allowed_email_domains', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('workspaces', sa.Column('allow_outside_guests', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('workspaces', sa.Column('require_google_sign_in', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('workspaces', sa.Column('require_two_step', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('workspaces', sa.Column('joiner_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('ck_workspace_members_workspace_role'), 'workspace_members', type_='check')
    op.create_check_constraint(op.f('ck_workspace_members_workspace_role'), 'workspace_members',
                               "role IN ('owner', 'admin', 'member', 'limited', 'guest')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE workspace_members SET role = 'guest' WHERE role = 'limited'")
    op.drop_constraint(op.f('ck_workspace_members_workspace_role'), 'workspace_members', type_='check')
    op.create_check_constraint(op.f('ck_workspace_members_workspace_role'), 'workspace_members',
                               "role IN ('owner', 'admin', 'member', 'guest')")
    op.drop_column('workspaces', 'joiner_plan')
    op.drop_column('workspaces', 'require_two_step')
    op.drop_column('workspaces', 'require_google_sign_in')
    op.drop_column('workspaces', 'allow_outside_guests')
    op.drop_column('workspaces', 'allowed_email_domains')
    op.drop_constraint(op.f('fk_workspace_members_deactivated_by_users'), 'workspace_members', type_='foreignkey')
    op.drop_column('workspace_members', 'deactivated_by')
    op.drop_column('workspace_members', 'deactivated_at')
    op.drop_column('workspace_members', 'takes_interviews')
    op.drop_column('workspace_members', 'marriage_anniversary')
    op.drop_column('workspace_members', 'date_of_birth')
    op.drop_column('users', 'last_second_factor')
    op.drop_column('users', 'last_sign_in_provider')
    op.drop_column('users', 'avatar_key')
    op.drop_index(op.f('ix_person_tasks_user_id'), table_name='person_tasks')
    op.drop_index(op.f('ix_person_tasks_task_id'), table_name='person_tasks')
    op.drop_table('person_tasks')
    op.drop_index('ix_audit_events_workspace_time', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
