"""automations scheduled, notifications out, compliance

Revision ID: 5fa36f530a8b
Revises: a40dc39170d4
Create Date: 2026-09-22 17:30:24.797263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fa36f530a8b'
down_revision: Union[str, Sequence[str], None] = 'a40dc39170d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=100), nullable=False),
    sa.Column('device', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_push_subscriptions_endpoint'))
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('compliance_obligations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('authority', sa.String(length=60), nullable=True),
    sa.Column('frequency', sa.String(length=12), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('due_months', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("frequency IN ('monthly', 'quarterly', 'half_yearly', 'yearly')", name=op.f('ck_compliance_obligations_frequency_kind')),
    sa.CheckConstraint('due_day BETWEEN 1 AND 31', name=op.f('ck_compliance_obligations_day_range')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_compliance_obligations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_obligations')),
    sa.UniqueConstraint('workspace_id', 'code', name='uq_compliance_obligations_code')
    )
    op.create_index(op.f('ix_compliance_obligations_workspace_id'), 'compliance_obligations', ['workspace_id'], unique=False)
    op.create_table('client_compliance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('obligation_id', sa.Uuid(), nullable=False),
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('assignee_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_client_compliance_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_client_compliance_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obligation_id'], ['compliance_obligations.id'], name=op.f('fk_client_compliance_obligation_id_compliance_obligations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_client_compliance_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_compliance')),
    sa.UniqueConstraint('obligation_id', 'list_id', name='uq_client_compliance_once')
    )
    op.create_index(op.f('ix_client_compliance_list_id'), 'client_compliance', ['list_id'], unique=False)
    op.create_index(op.f('ix_client_compliance_workspace_id'), 'client_compliance', ['workspace_id'], unique=False)
    op.create_table('automation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['automations.id'], name=op.f('fk_automation_runs_rule_id_automations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_automation_runs_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_runs')),
    sa.UniqueConstraint('rule_id', 'task_id', 'key', name='uq_automation_runs_once')
    )
    op.create_index(op.f('ix_automation_runs_task_id'), 'automation_runs', ['task_id'], unique=False)
    op.create_table('compliance_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_compliance_id', sa.Uuid(), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_compliance_id'], ['client_compliance.id'], name=op.f('fk_compliance_tasks_client_compliance_id_client_compliance'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_compliance_tasks_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_tasks')),
    sa.UniqueConstraint('client_compliance_id', 'period_key', name='uq_compliance_tasks_period')
    )
    op.add_column('notifications', sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workspace_members', sa.Column('email_notifications', sa.String(length=10), server_default=sa.text("'daily'"), nullable=False))
    op.add_column('workspace_members', sa.Column('digest_hour', sa.Integer(), server_default=sa.text('8'), nullable=False))
    op.add_column('workspace_members', sa.Column('timezone', sa.String(length=64), server_default=sa.text("'Asia/Kolkata'"), nullable=False))
    op.add_column('workspace_members', sa.Column('last_digest_on', sa.Date(), nullable=True))
    op.add_column('workspace_members', sa.Column('weekly_team_digest', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('workspace_members', sa.Column('last_team_digest_on', sa.Date(), nullable=True))
    op.add_column('workspace_members', sa.Column('whatsapp_opt_in', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint(op.f('ck_automations_trigger_kind'), 'automations', type_='check')
    op.create_check_constraint(op.f('ck_automations_trigger_kind'), 'automations',
                               "trigger IN ('task_created', 'status_changed', 'due_soon', 'overdue', 'priority_changed', 'assignee_added')")
    op.drop_constraint(op.f('ck_automations_action_kind'), 'automations', type_='check')
    op.create_check_constraint(op.f('ck_automations_action_kind'), 'automations',
                               "action IN ('assign', 'notify', 'set_priority', 'set_status', 'escalate', 'add_tag')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM automations WHERE trigger NOT IN ('task_created', 'status_changed') OR action NOT IN ('assign', 'notify', 'set_priority', 'set_status')")
    op.drop_constraint(op.f('ck_automations_trigger_kind'), 'automations', type_='check')
    op.create_check_constraint(op.f('ck_automations_trigger_kind'), 'automations', "trigger IN ('task_created', 'status_changed')")
    op.drop_constraint(op.f('ck_automations_action_kind'), 'automations', type_='check')
    op.create_check_constraint(op.f('ck_automations_action_kind'), 'automations', "action IN ('assign', 'notify', 'set_priority', 'set_status')")
    op.drop_column('workspace_members', 'whatsapp_opt_in')
    op.drop_column('workspace_members', 'last_team_digest_on')
    op.drop_column('workspace_members', 'weekly_team_digest')
    op.drop_column('workspace_members', 'last_digest_on')
    op.drop_column('workspace_members', 'timezone')
    op.drop_column('workspace_members', 'digest_hour')
    op.drop_column('workspace_members', 'email_notifications')
    op.drop_column('notifications', 'pushed_at')
    op.drop_column('notifications', 'emailed_at')
    op.drop_table('compliance_tasks')
    op.drop_index(op.f('ix_automation_runs_task_id'), table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_index(op.f('ix_client_compliance_workspace_id'), table_name='client_compliance')
    op.drop_index(op.f('ix_client_compliance_list_id'), table_name='client_compliance')
    op.drop_table('client_compliance')
    op.drop_index(op.f('ix_compliance_obligations_workspace_id'), table_name='compliance_obligations')
    op.drop_table('compliance_obligations')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
