"""two-way calendar sync

Revision ID: 797cc2af52da
Revises: 6170a5530ac2
Create Date: 2026-09-22 20:43:40.982994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '797cc2af52da'
down_revision: Union[str, Sequence[str], None] = '6170a5530ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=10), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=True),
    sa.Column('calendar_id', sa.String(length=300), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('push_tasks', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('push_blocks', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('pull_events', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('google', 'microsoft')", name=op.f('ck_calendar_connections_provider')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_connections_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_calendar_connections_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_connections')),
    sa.UniqueConstraint('workspace_id', 'user_id', 'provider', name='uq_calendar_connections_one_per_provider')
    )
    op.create_index(op.f('ix_calendar_connections_user_id'), 'calendar_connections', ['user_id'], unique=False)
    op.create_table('calendar_sync_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=5), nullable=False),
    sa.Column('local_id', sa.Uuid(), nullable=False),
    sa.Column('remote_id', sa.String(length=300), nullable=False),
    sa.Column('agreed', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('task', 'block')", name=op.f('ck_calendar_sync_items_kind')),
    sa.ForeignKeyConstraint(['connection_id'], ['calendar_connections.id'], name=op.f('fk_calendar_sync_items_connection_id_calendar_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_sync_items')),
    sa.UniqueConstraint('connection_id', 'kind', 'local_id', name='uq_calendar_sync_items_local')
    )
    op.create_index(op.f('ix_calendar_sync_items_connection_id'), 'calendar_sync_items', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_sync_items_connection_id'), table_name='calendar_sync_items')
    op.drop_table('calendar_sync_items')
    op.drop_index(op.f('ix_calendar_connections_user_id'), table_name='calendar_connections')
    op.drop_table('calendar_connections')
    # ### end Alembic commands ###
