"""work hierarchy

Revision ID: c16fa5eeb7c8
Revises: 
Create Date: 2026-09-21 14:34:09.033739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c16fa5eeb7c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workspaces_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_table('spaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('orderindex', sa.Float(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_spaces_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_spaces_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spaces'))
    )
    op.create_index(op.f('ix_spaces_workspace_id'), 'spaces', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'guest', name='workspace_role', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id', name=op.f('pk_workspace_members'))
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('parent_folder_id', sa.Uuid(), nullable=True),
    sa.Column('override_statuses', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('orderindex', sa.Float(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_folders_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folders.id'], name=op.f('fk_folders_parent_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_folders_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders'))
    )
    op.create_index(op.f('ix_folders_parent_folder_id'), 'folders', ['parent_folder_id'], unique=False)
    op.create_index(op.f('ix_folders_space_id'), 'folders', ['space_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('fg_color', sa.String(length=7), nullable=False),
    sa.Column('bg_color', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_tags_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_space_id'), 'tags', ['space_id'], unique=False)
    op.create_index('uq_tags_space_name', 'tags', ['space_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('override_statuses', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('orderindex', sa.Float(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_lists_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_lists_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_lists_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lists'))
    )
    op.create_index(op.f('ix_lists_folder_id'), 'lists', ['folder_id'], unique=False)
    op.create_index(op.f('ix_lists_space_id'), 'lists', ['space_id'], unique=False)
    op.create_table('statuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('list_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('status_group', sa.Enum('not_started', 'active', 'done', 'closed', name='status_group', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('orderindex', sa.Integer(), nullable=False),
    sa.CheckConstraint('num_nonnulls(space_id, folder_id, list_id) = 1', name=op.f('ck_statuses_one_scope')),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_statuses_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_statuses_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_statuses_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statuses'))
    )
    op.create_index(op.f('ix_statuses_folder_id'), 'statuses', ['folder_id'], unique=False)
    op.create_index(op.f('ix_statuses_list_id'), 'statuses', ['list_id'], unique=False)
    op.create_index(op.f('ix_statuses_space_id'), 'statuses', ['space_id'], unique=False)
    op.create_index('uq_statuses_folder_id_name', 'statuses', ['folder_id', sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('folder_id IS NOT NULL'))
    op.create_index('uq_statuses_list_id_name', 'statuses', ['list_id', sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('list_id IS NOT NULL'))
    op.create_index('uq_statuses_space_id_name', 'statuses', ['space_id', sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('space_id IS NOT NULL'))
    op.create_table('views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('list_id', sa.Uuid(), nullable=True),
    sa.Column('view_type', sa.Enum('list', 'board', 'calendar', 'dashboard', name='view_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('orderindex', sa.Float(), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(space_id, folder_id, list_id) = 1', name=op.f('ck_views_one_parent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_views_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_views_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_views_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_views_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_views'))
    )
    op.create_index(op.f('ix_views_folder_id'), 'views', ['folder_id'], unique=False)
    op.create_index(op.f('ix_views_list_id'), 'views', ['list_id'], unique=False)
    op.create_index(op.f('ix_views_space_id'), 'views', ['space_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('top_level_parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_estimate_seconds', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('orderindex', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('date_done', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_closed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('due_date IS NULL OR start_date IS NULL OR due_date >= start_date', name=op.f('ck_tasks_due_after_start')),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_tasks_not_own_parent')),
    sa.CheckConstraint('priority BETWEEN 1 AND 4', name=op.f('ck_tasks_priority_range')),
    sa.CheckConstraint('time_estimate_seconds >= 0', name=op.f('ck_tasks_estimate_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_tasks_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], name=op.f('fk_tasks_parent_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_tasks_status_id_statuses')),
    sa.ForeignKeyConstraint(['top_level_parent_id'], ['tasks.id'], name=op.f('fk_tasks_top_level_parent_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_list_id'), 'tasks', ['list_id'], unique=False)
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tasks_status_id'), 'tasks', ['status_id'], unique=False)
    op.create_index(op.f('ix_tasks_top_level_parent_id'), 'tasks', ['top_level_parent_id'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Enum('view', 'comment', 'edit', 'full', name='permission_level', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('list_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('granted_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(space_id, folder_id, list_id, task_id) = 1', name=op.f('ck_shares_one_target')),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_shares_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_shares_granted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_shares_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_shares_space_id_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_shares_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shares_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shares'))
    )
    op.create_index(op.f('ix_shares_folder_id'), 'shares', ['folder_id'], unique=False)
    op.create_index(op.f('ix_shares_list_id'), 'shares', ['list_id'], unique=False)
    op.create_index(op.f('ix_shares_space_id'), 'shares', ['space_id'], unique=False)
    op.create_index(op.f('ix_shares_task_id'), 'shares', ['task_id'], unique=False)
    op.create_index(op.f('ix_shares_user_id'), 'shares', ['user_id'], unique=False)
    op.create_index('uq_shares_user_folder_id', 'shares', ['user_id', 'folder_id'], unique=True, postgresql_where=sa.text('folder_id IS NOT NULL'))
    op.create_index('uq_shares_user_list_id', 'shares', ['user_id', 'list_id'], unique=True, postgresql_where=sa.text('list_id IS NOT NULL'))
    op.create_index('uq_shares_user_space_id', 'shares', ['user_id', 'space_id'], unique=True, postgresql_where=sa.text('space_id IS NOT NULL'))
    op.create_index('uq_shares_user_task_id', 'shares', ['user_id', 'task_id'], unique=True, postgresql_where=sa.text('task_id IS NOT NULL'))
    op.create_table('task_assignees',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_assignees_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_assignees_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id', name=op.f('pk_task_assignees'))
    )
    op.create_index(op.f('ix_task_assignees_user_id'), 'task_assignees', ['user_id'], unique=False)
    op.create_table('task_tags',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_task_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_tags_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id', name=op.f('pk_task_tags'))
    )
    op.create_index(op.f('ix_task_tags_tag_id'), 'task_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_tags_tag_id'), table_name='task_tags')
    op.drop_table('task_tags')
    op.drop_index(op.f('ix_task_assignees_user_id'), table_name='task_assignees')
    op.drop_table('task_assignees')
    op.drop_index('uq_shares_user_task_id', table_name='shares', postgresql_where=sa.text('task_id IS NOT NULL'))
    op.drop_index('uq_shares_user_space_id', table_name='shares', postgresql_where=sa.text('space_id IS NOT NULL'))
    op.drop_index('uq_shares_user_list_id', table_name='shares', postgresql_where=sa.text('list_id IS NOT NULL'))
    op.drop_index('uq_shares_user_folder_id', table_name='shares', postgresql_where=sa.text('folder_id IS NOT NULL'))
    op.drop_index(op.f('ix_shares_user_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_task_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_space_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_list_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_folder_id'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_tasks_top_level_parent_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_list_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_views_space_id'), table_name='views')
    op.drop_index(op.f('ix_views_list_id'), table_name='views')
    op.drop_index(op.f('ix_views_folder_id'), table_name='views')
    op.drop_table('views')
    op.drop_index('uq_statuses_space_id_name', table_name='statuses', postgresql_where=sa.text('space_id IS NOT NULL'))
    op.drop_index('uq_statuses_list_id_name', table_name='statuses', postgresql_where=sa.text('list_id IS NOT NULL'))
    op.drop_index('uq_statuses_folder_id_name', table_name='statuses', postgresql_where=sa.text('folder_id IS NOT NULL'))
    op.drop_index(op.f('ix_statuses_space_id'), table_name='statuses')
    op.drop_index(op.f('ix_statuses_list_id'), table_name='statuses')
    op.drop_index(op.f('ix_statuses_folder_id'), table_name='statuses')
    op.drop_table('statuses')
    op.drop_index(op.f('ix_lists_space_id'), table_name='lists')
    op.drop_index(op.f('ix_lists_folder_id'), table_name='lists')
    op.drop_table('lists')
    op.drop_index('uq_tags_space_name', table_name='tags')
    op.drop_index(op.f('ix_tags_space_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_folders_space_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_parent_folder_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_spaces_workspace_id'), table_name='spaces')
    op.drop_table('spaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
