"""leave holidays billing imports reminders

Revision ID: a40dc39170d4
Revises: 8dc9bb4f3720
Create Date: 2026-09-22 17:05:26.284413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40dc39170d4'
down_revision: Union[str, Sequence[str], None] = '8dc9bb4f3720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_holidays_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays')),
    sa.UniqueConstraint('workspace_id', 'day', name='uq_holidays_day')
    )
    op.create_index(op.f('ix_holidays_workspace_id'), 'holidays', ['workspace_id'], unique=False)
    op.create_table('imported_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_imported_records_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imported_records')),
    sa.UniqueConstraint('workspace_id', 'source', 'source_id', name='uq_imported_records_source')
    )
    op.create_table('leave_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('yearly_days', sa.Float(), nullable=True),
    sa.Column('paid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('needs_approval', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('orderindex', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_leave_types_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_types')),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_leave_types_name')
    )
    op.create_index(op.f('ix_leave_types_workspace_id'), 'leave_types', ['workspace_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('type_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('part', sa.String(length=12), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('approver_id', sa.String(length=128), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("part IN ('full', 'first_half', 'second_half')", name=op.f('ck_leave_requests_part_kind')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'cancelled')", name=op.f('ck_leave_requests_status_kind')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_leave_requests_ends_after_start')),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_leave_requests_approver_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_leave_requests_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_id'], ['leave_types.id'], name=op.f('fk_leave_requests_type_id_leave_types'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leave_requests_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_leave_requests_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests')),
    sa.UniqueConstraint('workspace_id', 'source_id', name='uq_leave_requests_source')
    )
    op.create_index(op.f('ix_leave_requests_user_id'), 'leave_requests', ['user_id'], unique=False)
    op.create_index('ix_leave_requests_workspace_dates', 'leave_requests', ['workspace_id', 'start_date', 'end_date'], unique=False)
    op.create_table('billing_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('list_id', sa.Uuid(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.CheckConstraint('num_nonnulls(space_id, folder_id, list_id) <= 1', name=op.f('ck_billing_rates_one_location')),
    sa.CheckConstraint('user_id IS NOT NULL OR num_nonnulls(space_id, folder_id, list_id) = 1', name=op.f('ck_billing_rates_someone_or_somewhere')),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_billing_rates_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_billing_rates_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_billing_rates_space_id_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_billing_rates_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_billing_rates_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_rates'))
    )
    op.create_index(op.f('ix_billing_rates_workspace_id'), 'billing_rates', ['workspace_id'], unique=False)
    op.create_table('client_fees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('list_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.CheckConstraint('num_nonnulls(space_id, folder_id, list_id) = 1', name=op.f('ck_client_fees_one_location')),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_client_fees_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_client_fees_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_client_fees_space_id_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_client_fees_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_fees')),
    sa.UniqueConstraint('folder_id', name=op.f('uq_client_fees_folder_id')),
    sa.UniqueConstraint('list_id', name=op.f('uq_client_fees_list_id')),
    sa.UniqueConstraint('space_id', name=op.f('uq_client_fees_space_id'))
    )
    op.create_index(op.f('ix_client_fees_workspace_id'), 'client_fees', ['workspace_id'], unique=False)
    op.add_column('timesheet_settings', sa.Column('reminders_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('timesheet_settings', sa.Column('reminder_weekday', sa.Integer(), server_default=sa.text('4'), nullable=False))
    op.add_column('timesheet_settings', sa.Column('reminder_hour', sa.Integer(), server_default=sa.text('16'), nullable=False))
    op.add_column('timesheet_settings', sa.Column('reminder_timezone', sa.String(length=64), server_default=sa.text("'Asia/Kolkata'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timesheet_settings', 'reminder_timezone')
    op.drop_column('timesheet_settings', 'reminder_hour')
    op.drop_column('timesheet_settings', 'reminder_weekday')
    op.drop_column('timesheet_settings', 'reminders_enabled')
    op.drop_index(op.f('ix_client_fees_workspace_id'), table_name='client_fees')
    op.drop_table('client_fees')
    op.drop_index(op.f('ix_billing_rates_workspace_id'), table_name='billing_rates')
    op.drop_table('billing_rates')
    op.drop_index('ix_leave_requests_workspace_dates', table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_user_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_leave_types_workspace_id'), table_name='leave_types')
    op.drop_table('leave_types')
    op.drop_table('imported_records')
    op.drop_index(op.f('ix_holidays_workspace_id'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
