"""people profiles and teams hub

Revision ID: b064fdc4aa80
Revises: cf0a461a86c1
Create Date: 2026-09-22 12:42:34.270928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b064fdc4aa80'
down_revision: Union[str, Sequence[str], None] = 'cf0a461a86c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('teams', sa.Column('handle', sa.String(length=64), nullable=True))
    op.add_column('teams', sa.Column('icon', sa.String(length=32), nullable=True))
    op.add_column('teams', sa.Column('locations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('auth_uid', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('name_from_profile', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # Everyone who exists so far signed in, so their sign-in id is their user id.
    op.execute("UPDATE users SET auth_uid = id")
    op.create_index(op.f('ix_users_auth_uid'), 'users', ['auth_uid'], unique=True)
    op.add_column('workspace_members', sa.Column('designation', sa.String(length=100), nullable=True))
    op.add_column('workspace_members', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('workspace_members', sa.Column('manager_id', sa.String(length=128), nullable=True))
    op.add_column('workspace_members', sa.Column('phone', sa.String(length=40), nullable=True))
    op.add_column('workspace_members', sa.Column('employee_code', sa.String(length=40), nullable=True))
    op.add_column('workspace_members', sa.Column('date_of_joining', sa.Date(), nullable=True))
    op.add_column('workspace_members', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('workspace_members', sa.Column('added_by', sa.String(length=128), nullable=True))
    op.add_column('workspace_members', sa.Column('invite_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_workspace_members_manager_id'), 'workspace_members', ['manager_id'], unique=False)
    op.create_foreign_key(op.f('fk_workspace_members_added_by_users'), 'workspace_members', 'users', ['added_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_workspace_members_manager_id_users'), 'workspace_members', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workspace_members_manager_id_users'), 'workspace_members', type_='foreignkey')
    op.drop_constraint(op.f('fk_workspace_members_added_by_users'), 'workspace_members', type_='foreignkey')
    op.drop_index(op.f('ix_workspace_members_manager_id'), table_name='workspace_members')
    op.drop_column('workspace_members', 'invite_sent_at')
    op.drop_column('workspace_members', 'added_by')
    op.drop_column('workspace_members', 'location')
    op.drop_column('workspace_members', 'date_of_joining')
    op.drop_column('workspace_members', 'employee_code')
    op.drop_column('workspace_members', 'phone')
    op.drop_column('workspace_members', 'manager_id')
    op.drop_column('workspace_members', 'department')
    op.drop_column('workspace_members', 'designation')
    op.drop_index(op.f('ix_users_auth_uid'), table_name='users')
    op.drop_column('users', 'name_from_profile')
    op.drop_column('users', 'auth_uid')
    op.drop_column('teams', 'locations')
    op.drop_column('teams', 'icon')
    op.drop_column('teams', 'handle')
    op.drop_column('teams', 'description')
    # ### end Alembic commands ###
