"""timesheets

Revision ID: 3a771c06dcd7
Revises: e06b5f7457ea
Create Date: 2026-09-21 18:29:15.489674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a771c06dcd7'
down_revision: Union[str, Sequence[str], None] = 'e06b5f7457ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_capacity',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('capacity_seconds', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_member_capacity_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_member_capacity_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id', name=op.f('pk_member_capacity'))
    )
    op.create_table('time_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('bg_color', sa.String(length=7), server_default='#e0e7ff', nullable=False),
    sa.Column('fg_color', sa.String(length=7), server_default='#3730a3', nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_time_tags_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_time_tags_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_tags'))
    )
    op.create_index(op.f('ix_time_tags_workspace_id'), 'time_tags', ['workspace_id'], unique=False)
    op.create_index('uq_time_tags_workspace_name', 'time_tags', ['workspace_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('timesheet_approvers',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('submitter_id', sa.String(length=128), nullable=False),
    sa.Column('approver_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_timesheet_approvers_approver_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], name=op.f('fk_timesheet_approvers_submitter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_timesheet_approvers_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'submitter_id', 'approver_id', name=op.f('pk_timesheet_approvers'))
    )
    op.create_table('timesheet_settings',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Integer(), server_default=sa.text('6'), nullable=False),
    sa.Column('approvals_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('capacity_seconds', sa.ARRAY(sa.Integer()), server_default=sa.text("'{28800,28800,28800,28800,28800,0,0}'"), nullable=False),
    sa.CheckConstraint('week_start BETWEEN 0 AND 6', name=op.f('ck_timesheet_settings_week_start_range')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_timesheet_settings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', name=op.f('pk_timesheet_settings'))
    )
    op.create_table('timesheet_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracked_seconds', sa.Integer(), nullable=False),
    sa.Column('billable_seconds', sa.Integer(), nullable=False),
    sa.Column('capacity_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'changes_needed', 'withdrawn')", name=op.f('ck_timesheet_submissions_status_values')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_timesheet_submissions_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_timesheet_submissions_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_timesheet_submissions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timesheet_submissions'))
    )
    op.create_index(op.f('ix_timesheet_submissions_user_id'), 'timesheet_submissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_timesheet_submissions_workspace_id'), 'timesheet_submissions', ['workspace_id'], unique=False)
    op.create_index('uq_timesheet_submissions_period', 'timesheet_submissions', ['workspace_id', 'user_id', 'period_start'], unique=True)
    op.create_table('timesheet_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('event', sa.String(length=24), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['timesheet_submissions.id'], name=op.f('fk_timesheet_comments_submission_id_timesheet_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_timesheet_comments_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timesheet_comments'))
    )
    op.create_index(op.f('ix_timesheet_comments_submission_id'), 'timesheet_comments', ['submission_id'], unique=False)
    op.create_table('timesheet_rows',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_timesheet_rows_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_timesheet_rows_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'task_id', 'period_start', name=op.f('pk_timesheet_rows'))
    )
    op.create_table('time_entry_tags',
    sa.Column('time_entry_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['time_tags.id'], name=op.f('fk_time_entry_tags_tag_id_time_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entries.id'], name=op.f('fk_time_entry_tags_time_entry_id_time_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time_entry_id', 'tag_id', name=op.f('pk_time_entry_tags'))
    )
    op.create_index(op.f('ix_time_entry_tags_tag_id'), 'time_entry_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_entry_tags_tag_id'), table_name='time_entry_tags')
    op.drop_table('time_entry_tags')
    op.drop_table('timesheet_rows')
    op.drop_index(op.f('ix_timesheet_comments_submission_id'), table_name='timesheet_comments')
    op.drop_table('timesheet_comments')
    op.drop_index('uq_timesheet_submissions_period', table_name='timesheet_submissions')
    op.drop_index(op.f('ix_timesheet_submissions_workspace_id'), table_name='timesheet_submissions')
    op.drop_index(op.f('ix_timesheet_submissions_user_id'), table_name='timesheet_submissions')
    op.drop_table('timesheet_submissions')
    op.drop_table('timesheet_settings')
    op.drop_table('timesheet_approvers')
    op.drop_index('uq_time_tags_workspace_name', table_name='time_tags')
    op.drop_index(op.f('ix_time_tags_workspace_id'), table_name='time_tags')
    op.drop_table('time_tags')
    op.drop_table('member_capacity')
    # ### end Alembic commands ###
