"""personal list

Revision ID: 90df7b962edf
Revises: 01993ab3edc3
Create Date: 2026-09-21 17:03:10.508825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90df7b962edf'
down_revision: Union[str, Sequence[str], None] = '01993ab3edc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaces', sa.Column('personal_owner_id', sa.String(length=128), nullable=True))
    op.create_index('uq_spaces_personal_per_user', 'spaces', ['workspace_id', 'personal_owner_id'], unique=True, postgresql_where=sa.text('personal_owner_id IS NOT NULL'))
    op.create_foreign_key(op.f('fk_spaces_personal_owner_id_users'), 'spaces', 'users', ['personal_owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_spaces_personal_owner_id_users'), 'spaces', type_='foreignkey')
    op.drop_index('uq_spaces_personal_per_user', table_name='spaces', postgresql_where=sa.text('personal_owner_id IS NOT NULL'))
    op.drop_column('spaces', 'personal_owner_id')
    # ### end Alembic commands ###
