"""time entries and overview view

Revision ID: 01993ab3edc3
Revises: 541af05dc620
Create Date: 2026-09-21 16:19:28.195411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01993ab3edc3'
down_revision: Union[str, Sequence[str], None] = '541af05dc620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


VIEW_TYPES_OLD = "('list', 'board', 'calendar', 'dashboard', 'workload')"
VIEW_TYPES_NEW = "('list', 'board', 'calendar', 'dashboard', 'workload', 'overview')"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('billable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(ended_at IS NULL) = (duration_seconds IS NULL)', name=op.f('ck_time_entries_finished_entries_have_duration')),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name=op.f('ck_time_entries_duration_non_negative')),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_time_entries_ends_after_start')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_time_entries_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_time_entries_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_time_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_entries'))
    )
    op.create_index(op.f('ix_time_entries_task_id'), 'time_entries', ['task_id'], unique=False)
    op.create_index(op.f('ix_time_entries_user_id'), 'time_entries', ['user_id'], unique=False)
    op.create_index('uq_time_entries_running_per_user', 'time_entries', ['user_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    # ### end Alembic commands ###

    # Hand-written: allow the new 'overview' view type in the enum's CHECK.
    op.drop_constraint(op.f('ck_views_view_type'), 'views', type_='check')
    op.create_check_constraint(op.f('ck_views_view_type'), 'views', f"view_type IN {VIEW_TYPES_NEW}")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM views WHERE view_type = 'overview'")
    op.drop_constraint(op.f('ck_views_view_type'), 'views', type_='check')
    op.create_check_constraint(op.f('ck_views_view_type'), 'views', f"view_type IN {VIEW_TYPES_OLD}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_time_entries_running_per_user', table_name='time_entries', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index(op.f('ix_time_entries_user_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_task_id'), table_name='time_entries')
    op.drop_table('time_entries')
    # ### end Alembic commands ###
