"""dashboards and team leads

Revision ID: e06b5f7457ea
Revises: 90df7b962edf
Create Date: 2026-09-21 17:35:34.439049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e06b5f7457ea'
down_revision: Union[str, Sequence[str], None] = '90df7b962edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('auto_refresh', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_dashboards_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_dashboards_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_dashboards_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboards'))
    )
    op.create_index(op.f('ix_dashboards_owner_id'), 'dashboards', ['owner_id'], unique=False)
    op.create_index(op.f('ix_dashboards_team_id'), 'dashboards', ['team_id'], unique=False)
    op.create_index(op.f('ix_dashboards_workspace_id'), 'dashboards', ['workspace_id'], unique=False)
    op.create_table('dashboard_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('card_type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('height BETWEEN 1 AND 6', name=op.f('ck_dashboard_cards_height_range')),
    sa.CheckConstraint('width BETWEEN 1 AND 12', name=op.f('ck_dashboard_cards_width_range')),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_cards_dashboard_id_dashboards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_cards'))
    )
    op.create_index(op.f('ix_dashboard_cards_dashboard_id'), 'dashboard_cards', ['dashboard_id'], unique=False)
    op.create_table('dashboard_shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.Enum('view', 'comment', 'edit', 'full', name='permission_level', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('granted_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(user_id, team_id) = 1', name=op.f('ck_dashboard_shares_one_grantee')),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_shares_dashboard_id_dashboards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_dashboard_shares_granted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_dashboard_shares_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dashboard_shares_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_shares'))
    )
    op.create_index(op.f('ix_dashboard_shares_dashboard_id'), 'dashboard_shares', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_team_id'), 'dashboard_shares', ['team_id'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_user_id'), 'dashboard_shares', ['user_id'], unique=False)
    op.create_index('uq_dashboard_shares_team', 'dashboard_shares', ['dashboard_id', 'team_id'], unique=True, postgresql_where=sa.text('team_id IS NOT NULL'))
    op.create_index('uq_dashboard_shares_user', 'dashboard_shares', ['dashboard_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('report_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('recipient_ids', sa.ARRAY(sa.String(length=128)), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('send_time', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency IN ('daily', 'weekdays', 'weekly', 'monthly')", name=op.f('ck_report_schedules_frequency_values')),
    sa.CheckConstraint('day_of_month IS NULL OR day_of_month BETWEEN 1 AND 28', name=op.f('ck_report_schedules_day_range')),
    sa.CheckConstraint('weekday IS NULL OR weekday BETWEEN 0 AND 6', name=op.f('ck_report_schedules_weekday_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_report_schedules_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_report_schedules_dashboard_id_dashboards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_schedules'))
    )
    op.create_index(op.f('ix_report_schedules_dashboard_id'), 'report_schedules', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_report_schedules_next_run_at'), 'report_schedules', ['next_run_at'], unique=False)
    op.create_table('report_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_by', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('recipients', sa.ARRAY(sa.String(length=320)), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_report_runs_dashboard_id_dashboards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['report_schedules.id'], name=op.f('fk_report_runs_schedule_id_report_schedules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_report_runs_triggered_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_runs'))
    )
    op.create_index(op.f('ix_report_runs_dashboard_id'), 'report_runs', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_report_runs_schedule_id'), 'report_runs', ['schedule_id'], unique=False)
    op.add_column('team_members', sa.Column('is_lead', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'is_lead')
    op.drop_index(op.f('ix_report_runs_schedule_id'), table_name='report_runs')
    op.drop_index(op.f('ix_report_runs_dashboard_id'), table_name='report_runs')
    op.drop_table('report_runs')
    op.drop_index(op.f('ix_report_schedules_next_run_at'), table_name='report_schedules')
    op.drop_index(op.f('ix_report_schedules_dashboard_id'), table_name='report_schedules')
    op.drop_table('report_schedules')
    op.drop_index('uq_dashboard_shares_user', table_name='dashboard_shares', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_dashboard_shares_team', table_name='dashboard_shares', postgresql_where=sa.text('team_id IS NOT NULL'))
    op.drop_index(op.f('ix_dashboard_shares_user_id'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_team_id'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_dashboard_id'), table_name='dashboard_shares')
    op.drop_table('dashboard_shares')
    op.drop_index(op.f('ix_dashboard_cards_dashboard_id'), table_name='dashboard_cards')
    op.drop_table('dashboard_cards')
    op.drop_index(op.f('ix_dashboards_workspace_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_team_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_owner_id'), table_name='dashboards')
    op.drop_table('dashboards')
    # ### end Alembic commands ###
