"""task links

Revision ID: 4872f3ee1685
Revises: 63a8d46c6f4f
Create Date: 2026-09-22 13:16:27.384884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4872f3ee1685'
down_revision: Union[str, Sequence[str], None] = '63a8d46c6f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('other_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('blocks', 'relates')", name=op.f('ck_task_links_kind')),
    sa.CheckConstraint('task_id <> other_id', name=op.f('ck_task_links_not_self')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_task_links_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['other_id'], ['tasks.id'], name=op.f('fk_task_links_other_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_links_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_links')),
    sa.UniqueConstraint('task_id', 'other_id', 'kind', name='pair')
    )
    op.create_index(op.f('ix_task_links_other_id'), 'task_links', ['other_id'], unique=False)
    op.create_index(op.f('ix_task_links_task_id'), 'task_links', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_links_task_id'), table_name='task_links')
    op.drop_index(op.f('ix_task_links_other_id'), table_name='task_links')
    op.drop_table('task_links')
    # ### end Alembic commands ###
