"""spaces tasks views phase d

Revision ID: 5249f258f1f1
Revises: 5fa36f530a8b
Create Date: 2026-09-22 19:17:40.851118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5249f258f1f1'
down_revision: Union[str, Sequence[str], None] = '5fa36f530a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

VIEW_OLD = ('list', 'board', 'calendar', 'dashboard', 'workload', 'overview', 'table', 'team', 'gantt', 'timeline', 'activity', 'form')
VIEW_NEW = VIEW_OLD + ('doc', 'whiteboard', 'mind_map', 'map', 'chat', 'embed')
FIELD_OLD = ('text', 'long_text', 'number', 'money', 'dropdown', 'labels', 'date', 'checkbox', 'email', 'phone', 'url', 'rating', 'progress', 'people')
FIELD_NEW = FIELD_OLD + ('location',)
TEMPLATE_OLD = ('task', 'list', 'folder')
TEMPLATE_NEW = TEMPLATE_OLD + ('space',)
FAV_OLD = ('space', 'folder', 'list', 'task', 'dashboard', 'view')
FAV_NEW = FAV_OLD + ('goal',)


def _checks(view, field, template, fav):
    for name, table, column, values in (
        ('ck_views_view_type', 'views', 'view_type', view),
        ('ck_custom_fields_field_type', 'custom_fields', 'field_type', field),
        ('ck_templates_template_kind', 'templates', 'template_kind', template),
        ('ck_favorites_kind', 'favorites', 'kind', fav),
    ):
        op.drop_constraint(op.f(name), table, type_='check')
        op.create_check_constraint(op.f(name), table, f"{column} IN {values}")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sidebar_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('orderindex', sa.Float(), nullable=False),
    sa.Column('space_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('collapsed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sidebar_sections_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sidebar_sections_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sidebar_sections'))
    )
    op.create_index(op.f('ix_sidebar_sections_user_id'), 'sidebar_sections', ['user_id'], unique=False)
    op.create_table('hidden_spaces',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_hidden_spaces_space_id_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hidden_spaces_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'space_id', name=op.f('pk_hidden_spaces'))
    )
    op.create_table('space_join_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'declined')", name=op.f('ck_space_join_requests_status')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_space_join_requests_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_space_join_requests_space_id_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_space_join_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_space_join_requests'))
    )
    op.create_index(op.f('ix_space_join_requests_space_id'), 'space_join_requests', ['space_id'], unique=False)
    op.create_index(op.f('ix_space_join_requests_user_id'), 'space_join_requests', ['user_id'], unique=False)
    op.create_table('view_contents',
    sa.Column('view_id', sa.Uuid(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_view_contents_updated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['view_id'], ['views.id'], name=op.f('fk_view_contents_view_id_views'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('view_id', name=op.f('pk_view_contents'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('view_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_chat_messages_task_id_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_messages_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['view_id'], ['views.id'], name=op.f('fk_chat_messages_view_id_views'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_table('inbound_emails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.String(length=300), nullable=False),
    sa.Column('list_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_inbound_emails_list_id_lists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_inbound_emails_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_emails')),
    sa.UniqueConstraint('message_id', name='uq_inbound_emails_message_id')
    )
    op.create_table('public_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=48), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('list_id', sa.Uuid(), nullable=True),
    sa.Column('view_id', sa.Uuid(), nullable=True),
    sa.Column('show_description', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('show_assignees', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('views_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('num_nonnulls(task_id, list_id, view_id) = 1', name=op.f('ck_public_links_one_target')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_public_links_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_public_links_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_public_links_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['view_id'], ['views.id'], name=op.f('fk_public_links_view_id_views'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_public_links_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_links')),
    sa.UniqueConstraint('token', name=op.f('uq_public_links_token'))
    )
    op.create_index(op.f('ix_public_links_list_id'), 'public_links', ['list_id'], unique=False)
    op.create_index(op.f('ix_public_links_task_id'), 'public_links', ['task_id'], unique=False)
    op.create_index(op.f('ix_public_links_view_id'), 'public_links', ['view_id'], unique=False)
    op.create_index(op.f('ix_public_links_workspace_id'), 'public_links', ['workspace_id'], unique=False)
    op.create_table('task_list_links',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('added_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_task_list_links_added_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_task_list_links_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_list_links_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'list_id', name=op.f('pk_task_list_links'))
    )
    op.create_index(op.f('ix_task_list_links_list_id'), 'task_list_links', ['list_id'], unique=False)
    op.add_column('folders', sa.Column('sprint_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('lists', sa.Column('email_token', sa.String(length=32), nullable=True))
    op.add_column('lists', sa.Column('sprint_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(op.f('uq_lists_email_token'), 'lists', ['email_token'])
    op.add_column('spaces', sa.Column('clickapps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('spaces', sa.Column('discoverable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tasks', sa.Column('points', sa.Float(), nullable=True))
    # ### end Alembic commands ###
    _checks(VIEW_NEW, FIELD_NEW, TEMPLATE_NEW, FAV_NEW)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM views WHERE view_type IN ('doc', 'whiteboard', 'mind_map', 'map', 'chat', 'embed')")
    op.execute("DELETE FROM custom_fields WHERE field_type = 'location'")
    op.execute("DELETE FROM templates WHERE template_kind = 'space'")
    op.execute("DELETE FROM favorites WHERE kind = 'goal'")
    _checks(VIEW_OLD, FIELD_OLD, TEMPLATE_OLD, FAV_OLD)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'points')
    op.drop_column('spaces', 'discoverable')
    op.drop_column('spaces', 'clickapps')
    op.drop_constraint(op.f('uq_lists_email_token'), 'lists', type_='unique')
    op.drop_column('lists', 'sprint_completed_at')
    op.drop_column('lists', 'email_token')
    op.drop_column('folders', 'sprint_settings')
    op.drop_index(op.f('ix_task_list_links_list_id'), table_name='task_list_links')
    op.drop_table('task_list_links')
    op.drop_index(op.f('ix_public_links_workspace_id'), table_name='public_links')
    op.drop_index(op.f('ix_public_links_view_id'), table_name='public_links')
    op.drop_index(op.f('ix_public_links_task_id'), table_name='public_links')
    op.drop_index(op.f('ix_public_links_list_id'), table_name='public_links')
    op.drop_table('public_links')
    op.drop_table('inbound_emails')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('view_contents')
    op.drop_index(op.f('ix_space_join_requests_user_id'), table_name='space_join_requests')
    op.drop_index(op.f('ix_space_join_requests_space_id'), table_name='space_join_requests')
    op.drop_table('space_join_requests')
    op.drop_table('hidden_spaces')
    op.drop_index(op.f('ix_sidebar_sections_user_id'), table_name='sidebar_sections')
    op.drop_table('sidebar_sections')
    # ### end Alembic commands ###
