"""planner lineup calendar feeds automations

Revision ID: c54d64d05b70
Revises: 991448cb5458
Create Date: 2026-09-22 13:52:55.991209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c54d64d05b70'
down_revision: Union[str, Sequence[str], None] = '991448cb5458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_feeds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_feeds_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_calendar_feeds_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_feeds'))
    )
    op.create_index(op.f('ix_calendar_feeds_user_id'), 'calendar_feeds', ['user_id'], unique=False)
    op.create_table('automations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('list_id', sa.Uuid(), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("action IN ('assign', 'notify', 'set_priority', 'set_status')", name=op.f('ck_automations_action_kind')),
    sa.CheckConstraint("trigger IN ('task_created', 'status_changed')", name=op.f('ck_automations_trigger_kind')),
    sa.CheckConstraint('num_nonnulls(space_id, folder_id, list_id) = 1', name=op.f('ck_automations_one_location')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_automations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_automations_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_automations_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_automations_space_id_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_automations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automations'))
    )
    op.create_index(op.f('ix_automations_folder_id'), 'automations', ['folder_id'], unique=False)
    op.create_index(op.f('ix_automations_list_id'), 'automations', ['list_id'], unique=False)
    op.create_index(op.f('ix_automations_space_id'), 'automations', ['space_id'], unique=False)
    op.create_index(op.f('ix_automations_workspace_id'), 'automations', ['workspace_id'], unique=False)
    op.create_table('lineup_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_lineup_items_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lineup_items_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_lineup_items_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineup_items')),
    sa.UniqueConstraint('user_id', 'task_id', name='once')
    )
    op.create_index(op.f('ix_lineup_items_task_id'), 'lineup_items', ['task_id'], unique=False)
    op.create_index(op.f('ix_lineup_items_user_id'), 'lineup_items', ['user_id'], unique=False)
    op.create_table('time_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_time_blocks_ends_after_start')),
    sa.CheckConstraint('task_id IS NOT NULL OR title IS NOT NULL', name=op.f('ck_time_blocks_task_or_title')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_time_blocks_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_time_blocks_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_time_blocks_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_blocks'))
    )
    op.create_index(op.f('ix_time_blocks_task_id'), 'time_blocks', ['task_id'], unique=False)
    op.create_index(op.f('ix_time_blocks_user_id'), 'time_blocks', ['user_id'], unique=False)
    op.add_column('workspace_members', sa.Column('home_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workspace_members', sa.Column('ical_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_workspace_members_ical_token'), 'workspace_members', ['ical_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_workspace_members_ical_token'), 'workspace_members', type_='unique')
    op.drop_column('workspace_members', 'ical_token')
    op.drop_column('workspace_members', 'home_layout')
    op.drop_index(op.f('ix_time_blocks_user_id'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_task_id'), table_name='time_blocks')
    op.drop_table('time_blocks')
    op.drop_index(op.f('ix_lineup_items_user_id'), table_name='lineup_items')
    op.drop_index(op.f('ix_lineup_items_task_id'), table_name='lineup_items')
    op.drop_table('lineup_items')
    op.drop_index(op.f('ix_automations_workspace_id'), table_name='automations')
    op.drop_index(op.f('ix_automations_space_id'), table_name='automations')
    op.drop_index(op.f('ix_automations_list_id'), table_name='automations')
    op.drop_index(op.f('ix_automations_folder_id'), table_name='automations')
    op.drop_table('automations')
    op.drop_index(op.f('ix_calendar_feeds_user_id'), table_name='calendar_feeds')
    op.drop_table('calendar_feeds')
    # ### end Alembic commands ###
