"""teams and workload views

Revision ID: 541af05dc620
Revises: c16fa5eeb7c8
Create Date: 2026-09-21 15:41:23.698857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541af05dc620'
down_revision: Union[str, Sequence[str], None] = 'c16fa5eeb7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


VIEW_TYPES_OLD = "('list', 'board', 'calendar', 'dashboard')"
VIEW_TYPES_NEW = "('list', 'board', 'calendar', 'dashboard', 'workload')"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_teams_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_teams_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_workspace_id'), 'teams', ['workspace_id'], unique=False)
    op.create_index('uq_teams_workspace_name', 'teams', ['workspace_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('team_members',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id', name=op.f('pk_team_members'))
    )
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.add_column('shares', sa.Column('team_id', sa.Uuid(), nullable=True))
    op.alter_column('shares', 'user_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_index(op.f('ix_shares_team_id'), 'shares', ['team_id'], unique=False)
    op.create_index('uq_shares_team_folder_id', 'shares', ['team_id', 'folder_id'], unique=True, postgresql_where=sa.text('folder_id IS NOT NULL AND team_id IS NOT NULL'))
    op.create_index('uq_shares_team_list_id', 'shares', ['team_id', 'list_id'], unique=True, postgresql_where=sa.text('list_id IS NOT NULL AND team_id IS NOT NULL'))
    op.create_index('uq_shares_team_space_id', 'shares', ['team_id', 'space_id'], unique=True, postgresql_where=sa.text('space_id IS NOT NULL AND team_id IS NOT NULL'))
    op.create_index('uq_shares_team_task_id', 'shares', ['team_id', 'task_id'], unique=True, postgresql_where=sa.text('task_id IS NOT NULL AND team_id IS NOT NULL'))
    op.create_foreign_key(op.f('fk_shares_team_id_teams'), 'shares', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # Hand-written: autogenerate does not see these.
    # A share goes to exactly one grantee: a person or a Team.
    op.create_check_constraint(op.f('ck_shares_one_grantee'), 'shares', 'num_nonnulls(user_id, team_id) = 1')
    # Enums are stored as strings guarded by CHECK; allow the new 'workload' view type.
    op.drop_constraint(op.f('ck_views_view_type'), 'views', type_='check')
    op.create_check_constraint(op.f('ck_views_view_type'), 'views', f"view_type IN {VIEW_TYPES_NEW}")


def downgrade() -> None:
    """Downgrade schema."""
    # Hand-written: undo the checks, and remove rows the old schema cannot hold.
    op.execute("DELETE FROM views WHERE view_type = 'workload'")
    op.drop_constraint(op.f('ck_views_view_type'), 'views', type_='check')
    op.create_check_constraint(op.f('ck_views_view_type'), 'views', f"view_type IN {VIEW_TYPES_OLD}")
    op.drop_constraint(op.f('ck_shares_one_grantee'), 'shares', type_='check')
    op.execute("DELETE FROM shares WHERE team_id IS NOT NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_shares_team_id_teams'), 'shares', type_='foreignkey')
    op.drop_index('uq_shares_team_task_id', table_name='shares', postgresql_where=sa.text('task_id IS NOT NULL AND team_id IS NOT NULL'))
    op.drop_index('uq_shares_team_space_id', table_name='shares', postgresql_where=sa.text('space_id IS NOT NULL AND team_id IS NOT NULL'))
    op.drop_index('uq_shares_team_list_id', table_name='shares', postgresql_where=sa.text('list_id IS NOT NULL AND team_id IS NOT NULL'))
    op.drop_index('uq_shares_team_folder_id', table_name='shares', postgresql_where=sa.text('folder_id IS NOT NULL AND team_id IS NOT NULL'))
    op.drop_index(op.f('ix_shares_team_id'), table_name='shares')
    op.alter_column('shares', 'user_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('shares', 'team_id')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index('uq_teams_workspace_name', table_name='teams')
    op.drop_index(op.f('ix_teams_workspace_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
