"""favourites task types ids view options list dates

Revision ID: 63a8d46c6f4f
Revises: b064fdc4aa80
Create Date: 2026-09-22 12:57:42.977487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a8d46c6f4f'
down_revision: Union[str, Sequence[str], None] = 'b064fdc4aa80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('orderindex', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('space', 'folder', 'list', 'task', 'dashboard', 'view')", name=op.f('ck_favorites_kind')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_favorites_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites'))
    )
    op.create_index('ix_favorites_user_workspace', 'favorites', ['user_id', 'workspace_id'], unique=False)
    op.create_index('uq_favorites_user_target', 'favorites', ['user_id', 'kind', 'target_id'], unique=True)
    op.create_table('task_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('name_plural', sa.String(length=40), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_milestone', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('orderindex', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_task_types_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_types'))
    )
    op.create_index(op.f('ix_task_types_workspace_id'), 'task_types', ['workspace_id'], unique=False)
    op.add_column('lists', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lists', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('spaces', sa.Column('task_prefix', sa.String(length=10), nullable=True))
    op.add_column('spaces', sa.Column('task_seq', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('tasks', sa.Column('seq', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('type_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tasks_type_id'), 'tasks', ['type_id'], unique=False)
    op.create_foreign_key(op.f('fk_tasks_type_id_task_types'), 'tasks', 'task_types', ['type_id'], ['id'], ondelete='SET NULL')
    op.add_column('views', sa.Column('private_to', sa.String(length=128), nullable=True))
    op.add_column('views', sa.Column('protected', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('views', sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_foreign_key(op.f('fk_views_private_to_users'), 'views', 'users', ['private_to'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # Hand-written: number existing tasks per Space, and give every Space a starting prefix.
    op.execute("""
        UPDATE tasks t SET seq = sub.rn FROM (
            SELECT t2.id, row_number() OVER (PARTITION BY l.space_id ORDER BY t2.created_at, t2.id) AS rn
            FROM tasks t2 JOIN lists l ON l.id = t2.list_id
        ) sub WHERE t.id = sub.id
    """)
    op.execute("""
        UPDATE spaces s SET task_seq = COALESCE((
            SELECT max(t.seq) FROM tasks t JOIN lists l ON l.id = t.list_id WHERE l.space_id = s.id
        ), 0)
    """)
    op.execute("""
        UPDATE spaces SET task_prefix = COALESCE(NULLIF(upper(left(regexp_replace(name, '[^A-Za-z0-9]', '', 'g'), 3)), ''), 'T')
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_views_private_to_users'), 'views', type_='foreignkey')
    op.drop_column('views', 'is_default')
    op.drop_column('views', 'protected')
    op.drop_column('views', 'private_to')
    op.drop_constraint(op.f('fk_tasks_type_id_task_types'), 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_type_id'), table_name='tasks')
    op.drop_column('tasks', 'type_id')
    op.drop_column('tasks', 'seq')
    op.drop_column('spaces', 'task_seq')
    op.drop_column('spaces', 'task_prefix')
    op.drop_column('lists', 'due_date')
    op.drop_column('lists', 'start_date')
    op.drop_index(op.f('ix_task_types_workspace_id'), table_name='task_types')
    op.drop_table('task_types')
    op.drop_index('uq_favorites_user_target', table_name='favorites')
    op.drop_index('ix_favorites_user_workspace', table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
