"""task groups recurrence list assignee

Revision ID: 35c1805bb590
Revises: 3a771c06dcd7
Create Date: 2026-09-21 19:12:47.329036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35c1805bb590'
down_revision: Union[str, Sequence[str], None] = '3a771c06dcd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('list_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('orderindex', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(space_id, folder_id, list_id) = 1', name=op.f('ck_task_groups_one_parent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_task_groups_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_task_groups_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_task_groups_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_task_groups_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_groups'))
    )
    op.create_index(op.f('ix_task_groups_folder_id'), 'task_groups', ['folder_id'], unique=False)
    op.create_index(op.f('ix_task_groups_list_id'), 'task_groups', ['list_id'], unique=False)
    op.create_index(op.f('ix_task_groups_space_id'), 'task_groups', ['space_id'], unique=False)
    op.add_column('lists', sa.Column('assignee_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_lists_assignee_id'), 'lists', ['assignee_id'], unique=False)
    op.create_foreign_key(op.f('fk_lists_assignee_id_users'), 'lists', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('group_id', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_next_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('recurs_from_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tasks_group_id'), 'tasks', ['group_id'], unique=False)
    op.create_index(op.f('ix_tasks_recurrence_next_at'), 'tasks', ['recurrence_next_at'], unique=False)
    op.create_foreign_key(op.f('fk_tasks_group_id_task_groups'), 'tasks', 'task_groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tasks_recurs_from_id_tasks'), 'tasks', 'tasks', ['recurs_from_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_recurs_from_id_tasks'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('fk_tasks_group_id_task_groups'), 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_recurrence_next_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_group_id'), table_name='tasks')
    op.drop_column('tasks', 'recurs_from_id')
    op.drop_column('tasks', 'recurrence_next_at')
    op.drop_column('tasks', 'recurrence')
    op.drop_column('tasks', 'group_id')
    op.drop_constraint(op.f('fk_lists_assignee_id_users'), 'lists', type_='foreignkey')
    op.drop_index(op.f('ix_lists_assignee_id'), table_name='lists')
    op.drop_column('lists', 'assignee_id')
    op.drop_index(op.f('ix_task_groups_space_id'), table_name='task_groups')
    op.drop_index(op.f('ix_task_groups_list_id'), table_name='task_groups')
    op.drop_index(op.f('ix_task_groups_folder_id'), table_name='task_groups')
    op.drop_table('task_groups')
    # ### end Alembic commands ###
